#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
Rscript 00_run_first.R "$@"

# The previous version of this file was commented-out and follows below:
#
# Rscript Fig1_US_map.R "$@"
# 
# # The previous version of this file was commented-out and follows below:
# #
# # Rscript Fig1_trend.R "$@"
# # 
# # # The previous version of this file was commented-out and follows below:
# # #
# # # Rscript Fig1_CE_map.R "$@"
# # # 
# # # # The previous version of this file was commented-out and follows below:
# # # #
# # # # Rscript 04_ARCH_sensitivity.R "$@"
# # # # 
# # # # # The previous version of this file was commented-out and follows below:
# # # # #
# # # # # Rscript 04_ARCH_sensitivity.R "$@"
# # # # # 
# # # # # # The previous version of this file was commented-out and follows below:
# # # # # #
# # # # # # Rscript Fig2b.R "$@"
# # # # # # 
# # # # # # # The previous version of this file was commented-out and follows below:
# # # # # # #
# # # # # # # Rscript Fig2d.R "$@"
# # # # # # # 
# # # # # # # # The previous version of this file was commented-out and follows below:
# # # # # # # #
# # # # # # # # Rscript Fig2c.R "$@"
# # # # # # # # 
# # # # # # # # # The previous version of this file was commented-out and follows below:
# # # # # # # # #
# # # # # # # # # Rscript Fig2.a.CE_map.R "$@"
# # # # # # # # # 
# # # # # # # # # # The previous version of this file was commented-out and follows below:
# # # # # # # # # #
# # # # # # # # # # Rscript Fig2.a.US_map.R "$@"
# # # # # # # # # # 
# # # # # # # # # # # The previous version of this file was commented-out and follows below:
# # # # # # # # # # #
# # # # # # # # # # # Rscript Fig2.a.US_map.R "$@"
# # # # # # # # # # # 
# # # # # # # # # # # # The previous version of this file was commented-out and follows below:
# # # # # # # # # # # #
# # # # # # # # # # # # Rscript Fig1_CE_map.R "$@"
# # # # # # # # # # # # 
# # # # # # # # # # # 
# # # # # # # # # # 
# # # # # # # # # 
# # # # # # # # 
# # # # # # # 
# # # # # # 
# # # # # 
# # # # 
# # # 
# # 
# 
